# Generated by Django 3.0.3 on 2020-02-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chave',
            name='chave',
            field=models.CharField(max_length=44),
        ),
    ]
