# Generated by Django 3.0.3 on 2020-02-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0002_auto_20200206_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='chave',
            name='pendente',
            field=models.BooleanField(default=False),
        ),
    ]
