# Generated by Django 3.0.3 on 2020-02-06 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0004_remove_chave_pendente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chave',
            old_name='chave',
            new_name='codigo',
        ),
    ]
